drop table if exists civil.`company`;
CREATE TABLE civil.`company` (
  `company_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'sequence',
  `user_id` VARCHAR(100) COMMENT 'user id',
  `email` VARCHAR(100)  COMMENT 'email',
  `company_name` VARCHAR(200) COMMENT 'company name',
  `industry_involved` VARCHAR(200) NOT NULL COMMENT '所属行业',
  `province` VARCHAR(100) NOT NULL COMMENT '省',
  `city` VARCHAR(100) NOT NULL COMMENT '市',
  `dist` VARCHAR(100) COMMENT '地级市',
  `address` VARCHAR(500) NOT NULL COMMENT '地址',
  `contactor` VARCHAR(50) COMMENT '联系人',
  `contact_no` VARCHAR(50) COMMENT '联系电话',
  `fax` VARCHAR(50) COMMENT 'fax',
  `qualification` VARCHAR(1000) COMMENT '资质填写',
  `self_introduction` VARCHAR(1000) COMMENT '自我介绍',
  `technical_support` VARCHAR(1000) COMMENT '技术支持',
  `verified` INT(1) default '0' COMMENT '0: not verified, 1: verified',
  `active_ind` INT(1) default '1' COMMENT '0: inactived, 1: activated',
  `deleted` INT(1) NOT NULL DEFAULT '0' COMMENT 'Soft delete',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT 'create time',
  `created_by` VARCHAR(100) default 'Auto' COMMENT 'create by',
  `updated_at`DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  `updated_by` VARCHAR(100) default 'Auto' COMMENT 'updated by',
  primary KEY (`company_id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;